Misc Python Cleanups
DIFI-Consortium/DIFI-Certification pull request #6
Opened 2022-08-23 20:41 UTC by 777arc

2022-08-24 18:51 UTC, jo-rivera requested changes

2022-08-24 18:51 UTC, jo-rivera commented on readme.md
> +s
typo?

2022-08-25 02:54 UTC, 777arc commented on readme.md
> +s
oops nice catch, i blame the cat

2022-08-25 20:20 UTC, FIU-ELF approved these changes

2022-08-25 20:29 UTC, jo-rivera approved these changes

2022-08-25 20:29 UTC, merged